using Godot;
using Newtonsoft.Json;
using OmoriSandbox.Battle;
using OmoriSandbox.Editor;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using OmoriSandbox.Animation;
using FileAccess = Godot.FileAccess;

namespace OmoriSandbox.Modding;

internal partial class ModManager : Node
{
	public static ModManager Instance;
	private const int ACTOR_SIZE = 106;

	public readonly Dictionary<string, Texture2D> Battlebacks = new();
	public readonly List<ModMetadata> LoadedMods = new();

	public override void _Ready()
	{
		Instance = this;

		if (!DirAccess.DirExistsAbsolute("user://mods"))
		{
			using DirAccess access = DirAccess.Open("user://");
			access.MakeDir("mods");
			GD.Print("Created user://mods directory");
		}

		if (!DirAccess.DirExistsAbsolute("user://mods/custom"))
		{
			using DirAccess access = DirAccess.Open("user://mods");
			access.MakeDir("custom");
			access.MakeDirRecursive("custom/battlebacks");
			access.MakeDirRecursive("custom/bgm");
			using FileAccess json = FileAccess.Open("user://mods/custom/mod.json", FileAccess.ModeFlags.Write);
			json.StoreString(JsonConvert.SerializeObject(new ModMetadata("custom", "My Custom Stuff", 
				"This mod is autogenerated by OmoriSandbox to allow easy importing of custom assets.", 
				"OmoriSandbox", "1.0.0", "")));
			
			using FileAccess readme = FileAccess.Open("user://mods/custom/README.txt", FileAccess.ModeFlags.Write);
			json.StoreString("""
			--- This mod was auto-generated by OmoriSandbox to allow easy importing of custom BGM and Battlebacks. ---
			
			Simply place your custom .ogg files in the 'bgm' folder and .png files in the 'battlebacks' folder.
			If you delete the 'custom' folder OmoriSandbox will regenerate it on the next launch.
			See https://github.com/EBro912/OmoriSandbox/wiki/Direct-File-Modding for more information.
			""");
			GD.Print("Autogenerated default custom mod");
		}
	}

	public void LoadMods()
	{
		GD.Print("Beginning mod loading...");
		int processed = 0;
		int total = 0;
		Stopwatch sw = Stopwatch.StartNew();

		foreach (string dirName in DirAccess.GetDirectoriesAt("user://mods"))
		{
			if (LoadMod(dirName))
				processed++;
			total++;
		}

		sw.Stop();
		GD.Print($"Loaded {processed}/{total} mods in {sw.ElapsedMilliseconds}ms");
		MainMenuManager.Instance.UpdateModsLoaded(processed, total);
	}

	private bool LoadMod(string dirName)
	{
		if (!FileAccess.FileExists($"user://mods/{dirName}/mod.json"))
		{
			GD.PushWarning($"Missing mod.json in {dirName}, skipping!");
			return false;
		}
		FileAccess access = FileAccess.Open($"user://mods/{dirName}/mod.json", FileAccess.ModeFlags.Read);

		ModMetadata metadata;
		try
		{
			metadata = JsonConvert.DeserializeObject<ModMetadata>(access.GetAsText());
			if (LoadedMods.Any(x => x.Id == metadata.Id))
			{
				GD.PushWarning($"Mod {metadata.Id} is already loaded, skipping!");
				return false;
			}
		}
		catch
		{
			GD.PushError($"Failed to read mod.json from mod {dirName}");
			return false;
		}

		foreach (string modDll in DirAccess.GetFilesAt("user://mods/" + dirName).Where(x => x.EndsWith(".dll")))
		{
			if (!LoadModAssembly($"{dirName}/{modDll}"))
				return false;
		}

		foreach (string modDir in DirAccess.GetDirectoriesAt("user://mods/" + dirName))
		{
			bool success = modDir.ToLower() switch
			{
				"actors" => LoadActors(dirName),
				"bgm" => LoadBGM(dirName),
				"sfx" => LoadSFX(dirName),
				"battlebacks" => LoadBattlebacks(dirName),
				"enemies" => LoadEnemies(dirName),
				"animations" => LoadAnimations(dirName),
				_ => true
			};
			if (!success)
				return false;
		}

		Texture2D icon = null;
		if (!string.IsNullOrEmpty(metadata.Icon) && metadata.Icon.EndsWith(".png"))
		{
			icon = ImageTexture.CreateFromImage(Image.LoadFromFile($"user://mods/{dirName}/{metadata.Icon}"));
		}

		MainMenuManager.Instance.AddModListEntry(metadata, icon);
		LoadedMods.Add(metadata);
		GD.Print($"Loaded {metadata.Name} ({metadata.Id})");
		return true;
	}

	private bool LoadModAssembly(string path)
	{
		try
		{
			AssemblyLoadContext context = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
			if (context == null)
				return false;
			Assembly asm = context.LoadFromAssemblyPath(ProjectSettings.GlobalizePath("user://mods/" + path));
			var type = asm.GetTypes().FirstOrDefault(t => t.IsSubclassOf(typeof(Mod)) && !t.IsAbstract);
			if (type == null)
			{
				GD.PushWarning($"No valid Mod class found in assembly {path}, skipping!");
				return false;
			}

			if (Activator.CreateInstance(type) is not Mod instance)
			{
				GD.PrintErr("Failed to instantiate Mod class from assembly " + path);
				return false;
			}

			AddChild(new ModContainer(instance));
			return true;
		}
		catch (Exception ex)
		{
			GD.PrintErr("Failed to load assembly " + path + ": " + ex);
			return false;
		}
	}

	private bool LoadActors(string root)
	{
		string path = "user://mods/" + root + "/actors";
		foreach (string actor in DirAccess.GetDirectoriesAt(path))
		{
			string[] files = DirAccess.GetFilesAt($"{path}/{actor}");
			string json = files.FirstOrDefault(x => x.EndsWith(".json"));
			if (json == null)
			{
				GD.PushWarning($"{root}: Missing json file at {path}/{actor}, skipping!");
				return false;
			}
			FileAccess access = FileAccess.Open($"{path}/{actor}/{json}", FileAccess.ModeFlags.Read);
			if (access == null)
			{
				GD.PushError($"{root}: Failed to open file {path}/{actor}/{json}");
				return false;
			}
			try
			{
				JsonActorMod mod = JsonConvert.DeserializeObject<JsonActorMod>(access.GetAsText());
				Database.RegisterJsonPartyMember(mod, BuildAnimation(mod, $"{path}/{actor}"));
			}
			catch
			{
				GD.PushError($"{root}: Failed to read actor json for {actor} from mod {root}");
				return false;
			}
		}
		return true;
	}

	private SpriteFrames BuildAnimation(JsonActorMod jsonActor, string path)
	{
		if (!FileAccess.FileExists($"{path}/{jsonActor.Atlas}"))
		{
			GD.PushWarning($"Unable to find atlas at {path}/{jsonActor.Atlas}, skipping!");
			return null;
		}
		SpriteFrames spriteFrames = new();
		Texture2D texture = ImageTexture.CreateFromImage(Image.LoadFromFile($"{path}/{jsonActor.Atlas}"));
		int columns = texture.GetWidth() / ACTOR_SIZE;
		foreach (JsonModAnimationData data in jsonActor.Animation)
		{
			spriteFrames.AddAnimation(data.Emotion);
			spriteFrames.SetAnimationSpeed(data.Emotion, data.Fps);
			spriteFrames.SetAnimationLoop(data.Emotion, true);
			foreach (int idx in data.Frames)
			{
				int column = idx % columns;
				int row = idx / columns;
				AtlasTexture tex = new()
				{
					Atlas = texture,
					Region = new Rect2(column * ACTOR_SIZE, row * ACTOR_SIZE, ACTOR_SIZE, ACTOR_SIZE)
				};
				spriteFrames.AddFrame(data.Emotion, tex);
			}
		}
		return spriteFrames;
	}

	private bool LoadEnemies(string root)
	{
		string path = "user://mods/" + root + "/enemies";
		foreach (string enemy in DirAccess.GetDirectoriesAt(path))
		{
			string[] files = DirAccess.GetFilesAt($"{path}/{enemy}");
			string json = files.FirstOrDefault(x => x.EndsWith(".json"));
			if (json == null)
			{
				GD.PushWarning($"{root}: Missing json file at {path}/{enemy}, skipping!");
				return false;
			}
			FileAccess access = FileAccess.Open($"{path}/{enemy}/{json}", FileAccess.ModeFlags.Read);
			if (access == null)
			{
				GD.PushError($"{root}: Failed to open file {path}/{enemy}/{json}");
				return false;
			}
			try
			{
				JsonEnemyMod mod = JsonConvert.DeserializeObject<JsonEnemyMod>(access.GetAsText());
				Database.RegisterJsonEnemy(mod, BuildAnimation(mod, $"{path}/{enemy}"));
			}
			catch (Exception e)
			{
				GD.PushError($"{root}: Failed to read enemy json for {enemy} from mod {root}");
				GD.PushError(e);
				return false;
			}
		}
		return true;
	}

	private SpriteFrames BuildAnimation(JsonEnemyMod jsonEnemy, string path)
	{
		if (!FileAccess.FileExists($"{path}/{jsonEnemy.Atlas}"))
		{
			GD.PushWarning($"Unable to find atlas at {path}/{jsonEnemy.Atlas}, skipping!");
			return null;
		}
		SpriteFrames spriteFrames = new();
		Texture2D texture = ImageTexture.CreateFromImage(Image.LoadFromFile($"{path}/{jsonEnemy.Atlas}"));
		int width = jsonEnemy.Width;
		int height = jsonEnemy.Height;
		int columns = texture.GetWidth() / width;
		foreach (JsonModAnimationData data in jsonEnemy.Animation)
		{
			spriteFrames.AddAnimation(data.Emotion);
			spriteFrames.SetAnimationSpeed(data.Emotion, data.Fps);
			spriteFrames.SetAnimationLoop(data.Emotion, true);
			foreach (int idx in data.Frames)
			{
				int column = idx % columns;
				int row = idx / columns;
				AtlasTexture tex = new()
				{
					Atlas = texture,
					Region = new Rect2(column * width, row * height, width, height)
				};
				spriteFrames.AddFrame(data.Emotion, tex);
			}
		}
		return spriteFrames;
	}

	private bool LoadBGM(string root)
	{
		string path = "user://mods/" + root + "/bgm";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".ogg"))
			{
				if (!AudioManager.Instance.LoadCustomBGM($"{path}/{file}"))
				{
					GD.PrintErr($"{root}: Failed to load custom BGM " + file);
					return false;
				}
			}
		}
		return true;
	}


	private bool LoadSFX(string root)
	{
		string path = "user://mods/" + root + "/sfx";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".ogg"))
			{
				if (!AudioManager.Instance.LoadCustomBGM($"{path}/{file}"))
				{
					GD.PrintErr($"{root}: Failed to load custom SFX " + file);
					return false;
				}
			}
		}
		return true;
	}

	private bool LoadBattlebacks(string root)
	{
		string path = "user://mods/" + root + "/battlebacks";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".png")) {
				if (!Battlebacks.TryAdd(file.GetBaseName(), ImageTexture.CreateFromImage(Image.LoadFromFile($"{path}/{file}"))))
				{
					GD.PrintErr($"{root}: Failed to load custom battleback " + file);
					return false;
				}
			}
		}
		return true;
	}

	private bool LoadAnimations(string root)
	{
		string path = "user://mods/" + root + "/animations";
		if (FileAccess.FileExists(path + "/Animations.json"))
			AnimationManager.Instance.LoadModded(root);
		if (FileAccess.FileExists(path + "/Animations.jsond"))
			AnimationManager.Instance.LoadDeltaPatch(root);
		return true;
	}
}
